language: scala
sudo: false
cache:
  matrix:
    include:
      - jdk: openjdk7
        scala: 2.10.4
        env: TEST_SPARK_VERSION="1.6.0"
      - jdk: oraclejdk7
        scala: 2.10.4
        env: TEST_SPARK_VERSION="1.6.0"
      - jdk: openjdk8
        scala: 2.11.7
        env: TEST_SPARK_VERSION="1.6.0"
      - jdk: oraclejdk8
        scala: 2.11.7
        env: TEST_SPARK_VERSION="1.6.0"
script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
after_success:
  - bash <(curl -s https://codecov.io/bash)

